avro-kotlin/avro4k

avro4k-core/src/main/kotlin/com/sksamuel/avro4k/decoder/RecordDecoder.kt, avro4k-core/src/test/kotlin/com/sksamuel/avro4k/decoder/NullableDecoderTest.kt
Hi,
The issue you've solved for encoding nested null records needs also to be addressed when decoding (https://github.com/sksamuel/avro4k/issues/2)
I'm submitting a pull request to address it. Can you check it please?
Thanks in advance.
Best regards,
Bruno Diaw
=> AvroDecoding :: Add support for nullable List of nested records

avro4k-core/src/main/kotlin/com/sksamuel/avro4k/AnnotationExtractor.kt, avro4k-core/src/main/kotlin/com/sksamuel/avro4k/annotations.kt, avro4k-core/src/main/kotlin/com/sksamuel/avro4k/schema/ClassSchemaFor.kt, avro4k-core/src/test/kotlin/com/sksamuel/avro4k/schema/AvroDefaultSchemaTest.kt, avro4k-core/src/test/resources/avro_default_annotation_float.json, avro4k-core/src/test/resources/avro_default_annotation_int.json, avro4k-core/src/test/resources/avro_default_annotation_string.json
Hey @sksamuel! Thank you for your work on this project; it's a great library.
For this feature, I followed the API provided by the [`@AvroDefault`](https://avro.apache.org/docs/1.8.0/api/java/org/apache/avro/reflect/AvroDefault.html) annotation. 
I was a little hesitant to have the function take in a `String`, but it is one of the simpler choices, and there's already an existing API that does it, so I think it's fine. I believe they define it as a JSON string.
Ideally it'd be a generic type, but you can't use generic types with annotation classes.
* Added the `@AvroDefault` in the same format as the other annotations in the project
* the key lines are these:
```kotlin
val default: Any? = annos.default()?.let {
when(fieldDescriptor.kind) {
PrimitiveKind.INT -> it.toInt()
PrimitiveKind.LONG …
```
=> Add @AvroDefault annotation

avro4k-core/src/main/kotlin/com/sksamuel/avro4k/decoder/ListDecoder.kt, avro4k-core/src/main/kotlin/com/sksamuel/avro4k/decoder/RecordDecoder.kt, avro4k-core/src/main/kotlin/com/sksamuel/avro4k/encoder/ListEncoder.kt, avro4k-core/src/main/kotlin/com/sksamuel/avro4k/encoder/RecordEncoder.kt, avro4k-core/src/main/kotlin/com/sksamuel/avro4k/schema/SchemaFor.kt, build.gradle
Started using this library together with ktor's ContentNegotiation with kotlinx.serialization. Unfortunately 0.20 couldn't be used with ktor 1.3.0 as ktor brings along kotlinx.serialization:0.14, causing the comparison for UnionKind.SEALED to fail, because the UnionKind.SEALED no longer exists in 0.14.
This PR bumps kotlinx.serialization to 0.14, and makes the necessary override changes for List/Record Encoder and Decoders.
=> Migrate to kotlinx.serialization 0.14

avro4k-core/src/main/kotlin/com/sksamuel/avro4k/AnnotationExtractor.kt, avro4k-core/src/main/kotlin/com/sksamuel/avro4k/annotations.kt, avro4k-core/src/test/kotlin/com/sksamuel/avro4k/schema/AvroAliasSchemaTest.kt, avro4k-core/src/test/resources/aliases_on_fields_multiple.json
Fix for #25 
Adding a new AvroAliases annotation that supports multiple aliases as in avro spec. I didn't reuse the AvroAlias annotation for this, because a list of strings is closer to the Avro spec.
=> Added new annotation @AvroAliases to support multiple aliases.

avro4k-core/src/main/kotlin/com/sksamuel/avro4k/Avro.kt, avro4k-core/src/main/kotlin/com/sksamuel/avro4k/schema/ClassSchemaFor.kt, avro4k-core/src/main/kotlin/com/sksamuel/avro4k/schema/SchemaFor.kt, avro4k-core/src/main/kotlin/com/sksamuel/avro4k/schema/schemas.kt, avro4k-core/src/test/kotlin/com/sksamuel/avro4k/schema/AvroDefaultSchemaTest.kt, avro4k-core/src/test/resources/avro_default_annotation_float.json, avro4k-core/src/test/resources/avro_default_annotation_int.json, avro4k-core/src/test/resources/avro_default_annotation_string.json
If a default is specified for a union, the default must be an instance of the first type in the union. Thus the generated schema needs to check the default definition when generating the union schema.
Additionally added a Avro.NULL constant that should be used to indicate a avro null default.
This is a fix for #27
=> Fixed incorrect handling of avro null default values.

avro4k-core/src/main/kotlin/com/sksamuel/avro4k/encoder/ByteArrayEncoder.kt, avro4k-core/src/test/kotlin/com/sksamuel/avro4k/encoder/ByteArrayEncoderTest.kt, avro4k-core/src/test/kotlin/com/sksamuel/avro4k/io/BasicIoTest.kt
This change will rewind all instances of `ByteBuffers` created by `ByteArrayEncoder` before returning the to the clients.
Fixes #55
=> Rewind created instances of ByteBuffer before returning them

.github/workflows/pr.yml, src/main/kotlin/com/sksamuel/avro4k/Avro.kt, src/main/kotlin/com/sksamuel/avro4k/SerialDescriptor.kt, src/main/kotlin/com/sksamuel/avro4k/schema/ClassSchemaFor.kt, src/test/kotlin/com/sksamuel/avro4k/decoder/AvroDefaultValuesDecoderTest.kt, src/test/kotlin/com/sksamuel/avro4k/schema/AvroDefaultSchemaTest.kt, src/test/resources/avro_default_annotation_big_decimal.json, src/test/resources/avro_default_annotation_list_of_records.json
Hi all,
Sorry I don't know what is the correct policy of contributing for the avro4k project. Example should I first raise an issue before opening a pull request. And another thing is that I'm not really that familiar with the kotlinx.serialization lib. 
But anyway can I suggest this small addition that would enable using the empty list default for more complex types than primitives. Sure the more correct solution would be adding full serialization for more complex default values but that probably would need more work.
Or this would be really helpful on my current project where we try to avoid using null default value for collections and just default those to empty list etc.
=> Add generic default value support

src/main/kotlin/com/github/avrokotlin/avro4k/serializer/date.kt, src/test/kotlin/com/github/avrokotlin/avro4k/decoder/DateDecoderTest.kt, src/test/kotlin/com/github/avrokotlin/avro4k/encoder/DateEncoderTest.kt
Hallo,
Added serializer to support that timestamp-micros logical type as there was this #70 issue. Don't know if there is too much need for this and sure no support for nanoseconds. But I guess with Java 9 and the increased precision of the clock might increase the demand.
=> Fix #70 - Add instant serializer with microseconds

build.gradle.kts, buildSrc/src/main/kotlin/Libs.kt, src/main/kotlin/com/github/avrokotlin/avro4k/Avro.kt, src/test/kotlin/com/github/avrokotlin/avro4k/schema/UserDefinedSerializerTest.kt
Updated kotlin to latest and avro minor version bump. 
Also there were some compiler warnings that bothered me. Probably nothing major but added compiler argument for that kotlin OptIn and changed Arvo class to use file suppression to fix import warning. Or now the build is free from warnings and allWarningsAsErrors kotlin option could be used.
I wonder why that dependency-bot doesn't automatically upgrade these?
=> Upgrade kotlin 1.4.10 -> 1.4.21 

src/main/kotlin/com/github/avrokotlin/avro4k/Avro.kt, src/test/kotlin/com/github/avrokotlin/avro4k/DefaultAvroTest.kt
Current code in SerializersModule is no op:
```kotlin
mapOf(
UUID::class to UUIDSerializer()
)
```
=> Use UUIDSerializer as contextual in Avro.default

src/main/kotlin/com/github/avrokotlin/avro4k/decoder/RecordDecoder.kt, src/test/kotlin/com/github/avrokotlin/avro4k/decoder/NestedClassDecoderTest.kt
Avro introduced a change here https://issues.apache.org/jira/browse/AVRO-2278 that changes the way get works. This breaks backwards compattible schema evolution. Previously if you tried to get an optional field that did not exist on the schema, you just got null. Now it throws an exception
=> If an optional field is missing from a previoius schema, do not blow up.

src/main/kotlin/com/github/avrokotlin/avro4k/schema/SchemaFor.kt, src/test/kotlin/com/github/avrokotlin/avro4k/decoder/ValueClassDecoderTest.kt, src/test/kotlin/com/github/avrokotlin/avro4k/encoder/ValueClassEncoderTest.kt, src/test/kotlin/com/github/avrokotlin/avro4k/schema/ValueClassSchemaTest.kt, src/test/resources/value_class.json
Fixes serialization of:
```Kotlin
@JvmInline
value class SomeValueClass(val a: TypeWithContextualSerializer)
```
=> Fix contextual serialization inside value classes

src/main/kotlin/com/github/avrokotlin/avro4k/encoder/RecordEncoder.kt
It's a very little improvement, but seems  great to prevent allocating 16 items lists while we have 3 fields avro schema 😄
=> perf: Build list with initial capacity

README.md, src/main/kotlin/com/github/avrokotlin/avro4k/Avro.kt, src/main/kotlin/com/github/avrokotlin/avro4k/AvroConfiguration.kt, src/main/kotlin/com/github/avrokotlin/avro4k/schema/ClassSchemaFor.kt, src/main/kotlin/com/github/avrokotlin/avro4k/schema/SchemaFor.kt, src/main/kotlin/com/github/avrokotlin/avro4k/schema/UnionSchemaFor.kt, src/test/kotlin/com/github/avrokotlin/avro4k/schema/NullableWithDefaultsSchemaTest.kt, src/test/resources/nullables-with-defaults.json
Quick PR that have no impact on the existing features. I hope you will release it before the work of primitives in root :pray:
=> feat: Set default to null when the field type is nullable (activable by the configuration)

buildSrc/src/main/kotlin/Libs.kt
New `snappy-java` version fixes [multiple security vulnerabilities](https://github.com/xerial/snappy-java/releases/tag/v1.1.10.1)
=> Bump snappy-java version

src/main/kotlin/com/github/avrokotlin/avro4k/AnnotationExtractor.kt, src/main/kotlin/com/github/avrokotlin/avro4k/annotations.kt, src/main/kotlin/com/github/avrokotlin/avro4k/schema/ClassSchemaFor.kt, src/test/kotlin/com/github/avrokotlin/avro4k/schema/AvroJsonPropSchemaTest.kt, src/test/resources/props_json_annotation_class.json, src/test/resources/props_json_annotation_field.json, src/test/resources/props_json_annotation_scala_enum.json
Avro AVSC allows for custom annotations as shown [here](https://issues.apache.org/jira/browse/AVRO-3026).
Same functionality can be partially achieved by using `@AvroProp` annotation, but only for single value annotations. 
For cases - like the linked issue, where a list of values is needed, existing annotation is not enough.
Therefore I'm suggesting adding `@AvropProps("name", "valueA", "valueB", "etc")`
=> properties with list of values

src/main/kotlin/com/github/avrokotlin/avro4k/annotations.kt
tested `AvroJsonProp` on my computer and the json language injection is not working. After a quick check, tldr: replace `@Language("json")` by `@Language("JSON")`.
Longer story: language injection is done by intellij, and we can find all the languages in `Parameters > Editor > Language injections`. We should set a value found inside the `Language` column, where we can only find `JSON` and not `json`, maybe it's case sensitive!
If still not working, let's remove the annotation then!
=> fix(annotations): Set the `@Language` value to `JSON`

build.gradle.kts, src/main/kotlin/com/github/avrokotlin/avro4k/AnnotationExtractor.kt, src/main/kotlin/com/github/avrokotlin/avro4k/annotations.kt, src/test/kotlin/com/github/avrokotlin/avro4k/schema/AvroAliasSchemaTest.kt, src/test/kotlin/com/github/avrokotlin/avro4k/schema/EnumSchemaTest.kt
- Now, to have multiple aliases, just annotate like `@AvroAlias("alias1", "alias2", "alias3")` as it is now a vararg parameter
- updated to kotlin 1.9 to have `@Repeatable` working
- deprecated `@AvroAliases` in favor of `@AvroAlias`
- Closes #155
=> feat(aliases): Merge AvroAliases annotation to AvroAlias

src/main/kotlin/com/github/avrokotlin/avro4k/FieldNaming.kt, src/main/kotlin/com/github/avrokotlin/avro4k/decoder/RecordDecoder.kt, src/test/kotlin/com/github/avrokotlin/avro4k/decoder/AvroAliasTest.kt
Problem: We want to read some data using Avro evolution mechanism for field renaming. Current behavior does not account for AvroAlias annotation.
Proposed solution: fieldValue() function iterates through list of possible field names, starting with the resolvedFieldName. For each attempt, if record contains the field name, return the value returned from record.get(...), else continue.
Closes #170
=> Added support for decoding with avro alias

src/main/kotlin/com/github/avrokotlin/avro4k/annotations.kt, src/main/kotlin/com/github/avrokotlin/avro4k/schema/SchemaFor.kt, src/main/kotlin/com/github/avrokotlin/avro4k/serializer/BigDecimalSerializer.kt, src/test/kotlin/com/github/avrokotlin/avro4k/decoder/AvroDefaultValuesDecoderTest.kt, src/test/kotlin/com/github/avrokotlin/avro4k/schema/BigDecimalSchemaTest.kt
- `ScalePrecision` annotation is removed, as `scale` and `precision` params moved to `AvroDecimalLogicalType` (Closes #189)
=> feat: Merge ScalePrecision to AvroDecimalLogicalType

src/main/kotlin/com/github/avrokotlin/avro4k/decoder/ListDecoder.kt, src/main/kotlin/com/github/avrokotlin/avro4k/decoder/MapDecoder.kt, src/main/kotlin/com/github/avrokotlin/avro4k/encoder/ListEncoder.kt, src/main/kotlin/com/github/avrokotlin/avro4k/encoder/MapEncoder.kt, src/test/kotlin/com/github/avrokotlin/avro4k/endecode/ArrayEncoderTest.kt, src/test/kotlin/com/github/avrokotlin/avro4k/endecode/MapEncoderTest.kt
=> fix: Allow encoding null array items or null map values

src/main/kotlin/com/github/avrokotlin/avro4k/Avro.kt, src/main/kotlin/com/github/avrokotlin/avro4k/annotations.kt, src/main/kotlin/com/github/avrokotlin/avro4k/decoder/AvroTaggedDecoder.kt, src/main/kotlin/com/github/avrokotlin/avro4k/internal/EnumResolver.kt, src/main/kotlin/com/github/avrokotlin/avro4k/schema/ValueVisitor.kt, src/main/kotlin/com/github/avrokotlin/avro4k/schema/VisitorContext.kt, src/test/kotlin/com/github/avrokotlin/avro4k/AvroObjectContainerFileTest.kt, src/test/kotlin/com/github/avrokotlin/avro4k/encoding/EnumEncodingTest.kt, src/test/kotlin/com/github/avrokotlin/avro4k/schema/AvroNamespaceOverrideSchemaTest.kt, src/test/kotlin/com/github/avrokotlin/avro4k/schema/AvroPropsSchemaTest.kt, src/test/kotlin/com/github/avrokotlin/avro4k/schema/EnumSchemaTest.kt
Closes #200
- `AvroEnumDefault` doesn't have a value now, and must be put on an enum value instead of the enum class itself
=> feat!: Set @AvroEnumDefault directly to the enum value instead of the class

src/main/kotlin/com/github/avrokotlin/avro4k/internal/SerializerLocatorMiddleware.kt, src/main/kotlin/com/github/avrokotlin/avro4k/internal/decoder/direct/AbstractAvroDirectDecoder.kt, src/main/kotlin/com/github/avrokotlin/avro4k/internal/decoder/direct/CollectionsDirectDecoder.kt, src/main/kotlin/com/github/avrokotlin/avro4k/internal/decoder/generic/CollectionGenericDecoders.kt, src/main/kotlin/com/github/avrokotlin/avro4k/internal/encoder/direct/AbstractAvroDirectEncoder.kt, src/main/kotlin/com/github/avrokotlin/avro4k/internal/encoder/direct/CollectionsEncoder.kt, src/main/kotlin/com/github/avrokotlin/avro4k/internal/schema/ValueVisitor.kt, src/test/kotlin/com/github/avrokotlin/avro4k/AvroAssertions.kt, src/test/kotlin/com/github/avrokotlin/avro4k/encoding/AvroFixedEncodingTest.kt, src/test/kotlin/com/github/avrokotlin/avro4k/encoding/BytesEncodingTest.kt, src/test/kotlin/com/github/avrokotlin/avro4k/schema/BytesSchemaTest.kt
=> fix: Only handle ByteArrays as bytes or fixed, and collection of Byte as arrays of int

src/main/kotlin/com/github/avrokotlin/avro4k/internal/encoder/direct/AbstractAvroDirectEncoder.kt, src/main/kotlin/com/github/avrokotlin/avro4k/internal/encoder/generic/AbstractAvroGenericEncoder.kt, src/main/kotlin/com/github/avrokotlin/avro4k/internal/encoder/generic/FixedGenericEncoder.kt, src/main/kotlin/com/github/avrokotlin/avro4k/internal/helpers.kt, src/test/kotlin/com/github/avrokotlin/avro4k/encoding/AvroFixedEncodingTest.kt
=> fix: No more automatic padding for fixed type

benchmark/README.md, benchmark/build.gradle.kts, src/main/kotlin/com/github/avrokotlin/avro4k/Avro.kt, src/main/kotlin/com/github/avrokotlin/avro4k/internal/EnumResolver.kt, src/main/kotlin/com/github/avrokotlin/avro4k/internal/PolymorphicResolver.kt, src/main/kotlin/com/github/avrokotlin/avro4k/internal/RecordResolver.kt, src/test/kotlin/com/github/avrokotlin/avro4k/encoding/AvroFixedEncodingTest.kt, src/test/resources/fixed_string_5.json
Solves an issue of performance where WeakIdentityHashMap uses too early a synchronised block. Closes #303
=> chore: Use WeakHashMap instead of buggy WeakIdentityHashMap
